FROM python:3.10-slim

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1

CMD ["celery", "-A", "app.celery_app.celery", "worker", "--loglevel=info", "--concurrency=4", "--queues=default"]
